"""add account and transaction

Revision ID: 252bf0f85e02
Revises: e93ab981715f
Create Date: 2020-07-04 22:37:16.084710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '252bf0f85e02'
down_revision = 'e93ab981715f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('platinum', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('electrum', sa.Integer(), nullable=True),
    sa.Column('silver', sa.Integer(), nullable=True),
    sa.Column('copper', sa.Integer(), nullable=True),
    sa.CheckConstraint('copper >= 0', name='copper_gte_0'),
    sa.CheckConstraint('electrum >= 0', name='electrum_gte_0'),
    sa.CheckConstraint('gold >= 0', name='gold_gte_0'),
    sa.CheckConstraint('platinum >= 0', name='platinum_gte_0'),
    sa.CheckConstraint('silver >= 0', name='silver_gte_0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('platinum', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('electrum', sa.Integer(), nullable=True),
    sa.Column('silver', sa.Integer(), nullable=True),
    sa.Column('copper', sa.Integer(), nullable=True),
    sa.Column('running_total', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_timestamp'))

    op.drop_table('transaction')
    op.drop_table('account')
    # ### end Alembic commands ###
