"""add treasure

Revision ID: cf3d762dcb44
Revises: 252bf0f85e02
Create Date: 2020-07-05 11:10:08.290339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3d762dcb44'
down_revision = '252bf0f85e02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treasure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('treasure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_treasure_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treasure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_treasure_timestamp'))

    op.drop_table('treasure')
    # ### end Alembic commands ###
